package pricing

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// dataJSON is the pricing dataset compiled into the binary. Shipping it inline
// is what lets the tool stay fully offline at runtime: there is no network call
// anywhere in this package, and no cache directory to go stale or be poisoned.
// Refreshes arrive through a normal release, generated by `pricing sync`.
//
//go:embed data/pricing.json
var dataJSON []byte

// SchemaVersion is the dataset format this build understands. Bumped from the
// Python implementation's 1, which had no time dimension at all.
const SchemaVersion = 2

type fileFormat struct {
	Schema     int               `json:"schema"`
	Updated    Date              `json:"updated"`
	Sources    []string          `json:"sources,omitempty"`
	Models     map[string]*Model `json:"models"`
	ByProvider map[string]*Model `json:"by_provider,omitempty"`
	Aliases    map[string]string `json:"aliases,omitempty"`
}

var (
	once    sync.Once
	loaded  *Table
	loadErr error
)

// Load returns the pricing table, reading the embedded dataset once and then
// overlaying the user's own file if they have one.
func Load() (*Table, error) {
	once.Do(func() {
		loaded, loadErr = load()
	})
	return loaded, loadErr
}

// MustLoad is Load for callers that cannot proceed without pricing.
func MustLoad() *Table {
	t, err := Load()
	if err != nil {
		panic(err)
	}
	return t
}

func load() (*Table, error) {
	var f fileFormat
	if err := json.Unmarshal(dataJSON, &f); err != nil {
		return nil, fmt.Errorf("embedded pricing data is corrupt: %w", err)
	}
	if f.Schema != SchemaVersion {
		return nil, fmt.Errorf("embedded pricing data is schema %d, this build expects %d", f.Schema, SchemaVersion)
	}
	tbl := &Table{
		Updated:    f.Updated,
		Models:     f.Models,
		ByProvider: f.ByProvider,
		Aliases:    f.Aliases,
	}
	if tbl.Models == nil {
		tbl.Models = map[string]*Model{}
	}
	if tbl.ByProvider == nil {
		tbl.ByProvider = map[string]*Model{}
	}
	if tbl.Aliases == nil {
		tbl.Aliases = map[string]string{}
	}
	for id, m := range tbl.Models {
		m.ID = id
		sortRates(m)
	}
	for _, m := range tbl.ByProvider {
		sortRates(m)
	}
	applyOverride(tbl)
	return tbl, nil
}

// applyOverride merges ~/.tokentelemetry/pricing.json over the embedded table,
// so a user can correct a rate we got wrong (or price an internal model we have
// never heard of) without waiting for a release. Failures are silent by design:
// a malformed override must degrade to shipped prices, not break the tool.
func applyOverride(tbl *Table) {
	path := os.Getenv("TT_PRICING_FILE")
	if path == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return
		}
		path = filepath.Join(home, ".tokentelemetry", "pricing.json")
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return
	}
	var f fileFormat
	if err := json.Unmarshal(raw, &f); err != nil {
		return
	}
	for id, m := range f.Models {
		if m == nil || len(m.Rates) == 0 {
			continue
		}
		m.ID = id
		sortRates(m)
		key := Normalize(id)
		tbl.Models[key] = m
		// Provider-keyed entries are consulted BEFORE the flat table, so a
		// bundled one would silently win over the override the user just wrote
		// — the override would appear to do nothing for any agent that records
		// its provider. Overriding a model drops the shipped per-provider rates
		// for it; the file can restore any it still wants under by_provider.
		for pk := range tbl.ByProvider {
			if i := strings.Index(pk, providerSep); i >= 0 && pk[i+1:] == key {
				delete(tbl.ByProvider, pk)
			}
		}
	}
	for key, m := range f.ByProvider {
		if m == nil || len(m.Rates) == 0 {
			continue
		}
		sortRates(m)
		tbl.ByProvider[key] = m
	}
	for from, to := range f.Aliases {
		tbl.Aliases[Normalize(from)] = Normalize(to)
	}
}

func sortRates(m *Model) {
	// Insertion sort: rate series are tiny (a handful of entries) and usually
	// already ordered, so this beats pulling in sort machinery per model.
	for i := 1; i < len(m.Rates); i++ {
		for j := i; j > 0 && m.Rates[j].From.Before(m.Rates[j-1].From); j-- {
			m.Rates[j], m.Rates[j-1] = m.Rates[j-1], m.Rates[j]
		}
	}
}
